project_id = "iygbnnvsojlgztqvcghy"

[functions.generate-playlist]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-callback]
verify_jwt = false

[functions.jamendo-proxy]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.weekly-digest]
verify_jwt = false